version: '3'
services:

  mysql8:
    image: mysql:8.0.22
    container_name: mysql8
    networks:
      - bridge
    ports:
      - 3306:3306
    environment:
      TZ: Etc/UTC
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - mysql8-data:/var/lib/mysql
      - ./docker/mysql8/init:/docker-entrypoint-initdb.d

  jwtapp:
    image: jwtapp:latest
    container_name: jwtapp
    networks:
      - bridge
    ports:
      - 8080:8080
    depends_on:
      - mysql8
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql8:3306/testdb?useSSL=false&characterEncoding=UTF8&connectionTimeZone=UTC&allowPublicKeyRetrieval=true


volumes:
  mysql8-data:

networks:
  bridge:
    driver: bridge